export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_FAVORITE_PRODUCTS = "FETCH_FAVORITE_PRODUCTS";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const PLACE_ORDER = "PLACE_ORDER";