export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_FAVORITE_PRODUCTS_SUCCESS = "FETCH_FAVORITE_PRODUCTS_SUCCESS";
export const FETCH_FAVORITE_PRODUCTS_FAILED = "FETCH_FAVORITE_PRODUCTS_FAILED";

export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";
export const ADD_TO_FAVORITES_FAILED = "ADD_TO_FAVORITES_FAILED";

export const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
export const REMOVE_FROM_FAVORITES_FAILED = "REMOVE_FROM_FAVORITES_FAILED";

export const TOGGLE_VERIFYING_TOKEN = "TOGGLE_VERIFYING_TOKEN";

export const TOGGLE_IS_WORKING = "TOGGLE_IS_WORKING";

export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
